config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # return all taks from db Task
  def index
    @tasks = Task.all
  end
  # return a task for id
  def show
    @tasks = Task.find(params[:id])
  end
  # create a task instance
  def new
    # create
    @task = Task.new
    
  end

  def create
    @task = Task.new(task_params)
    # save the task instance
    if @task.save
      # redirect to the tasks views
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<div>
  <% @tasks.each do |task| %>
    <div>
      <label><input type="checkbox" id="cbox1" value="first_checkbox"><%= link_to task.title, task_path(task)%></label>
    </div>
  <% end %>
</div>
<%= link_to "+ Add new task", tasks_new_path %>

app/views/tasks/new.html.erb
<div>
<h1>New task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<div>

app/views/tasks/show.html.erb
<div>
<h1><%= @tasks.title %></h1>
<div>
  <%= @tasks.details %>
</div>
<label><input type="checkbox">This task was complited</label>

</div>
<%= link_to "Back to tasks", tasks_path %>